# Generated by Django 3.1.2 on 2021-03-11 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoFront', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coininfo',
            old_name='initial',
            new_name='deposit',
        ),
    ]
